
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Aug 06 19:06:28 CEST 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHARACTER = 14;
  public static final int IDENT = 11;
  public static final int BOOL = 13;
  public static final int OPBRACKET = 3;
  public static final int NUMBER = 12;
  public static final int SEMI = 6;
  public static final int PROG = 2;
  public static final int EOF = 0;
  public static final int CLSQBRACKET = 10;
  public static final int COMMA = 8;
  public static final int ASSIGN = 7;
  public static final int error = 1;
  public static final int CLBRACKET = 4;
  public static final int OPSQBRACKET = 9;
  public static final int CONST = 5;
}

