
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Aug 06 13:18:07 CEST 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PROG = 2;
  public static final int error = 1;
  public static final int IDENT = 3;
  public static final int EOF = 0;
}

