
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Aug 22 16:42:39 CEST 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPBRACKET = 7;
  public static final int MAP = 39;
  public static final int CONST = 9;
  public static final int NOTEQUAL = 19;
  public static final int GREATER = 20;
  public static final int SEMI = 10;
  public static final int CONTINUE = 32;
  public static final int LESS = 22;
  public static final int MINUS = 25;
  public static final int CHARACTER = 5;
  public static final int AND = 40;
  public static final int CLPAREN = 16;
  public static final int LESSEQUAL = 23;
  public static final int OR = 41;
  public static final int BOOL = 4;
  public static final int COMMA = 12;
  public static final int INC = 42;
  public static final int DIV = 27;
  public static final int OPPAREN = 15;
  public static final int PLUS = 24;
  public static final int ASSIGN = 11;
  public static final int IF = 30;
  public static final int DOT = 37;
  public static final int EOF = 0;
  public static final int RETURN = 33;
  public static final int EQUAL = 18;
  public static final int NEW = 38;
  public static final int error = 1;
  public static final int MUL = 26;
  public static final int NUMBER = 3;
  public static final int MOD = 28;
  public static final int CLBRACKET = 8;
  public static final int BREAK = 31;
  public static final int IDENT = 2;
  public static final int VOID = 17;
  public static final int GREATEREQUAL = 21;
  public static final int COLON = 46;
  public static final int UNION = 29;
  public static final int ELSE = 44;
  public static final int READ = 34;
  public static final int WHILE = 36;
  public static final int PROG = 6;
  public static final int CLSQBRACKET = 14;
  public static final int DEC = 43;
  public static final int OPSQBRACKET = 13;
  public static final int PRINT = 45;
  public static final int DO = 35;
}

